# Generated by Django 4.2.7 on 2023-11-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_user_users_alter_event_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endtime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='starttime',
            field=models.TimeField(blank=True),
        ),
    ]
