# Generated by Django 4.2.7 on 2023-11-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_endtime_alter_event_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starttime',
        ),
    ]
