# Generated by Django 4.2.7 on 2023-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_endtime_remove_event_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.IntegerField(default=1),
        ),
    ]
