# Generated by Django 4.2.7 on 2023-11-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodtype', models.CharField(max_length=50)),
                ('foodname', models.CharField(max_length=50)),
                ('foodprice', models.FloatField()),
                ('foodquantity', models.IntegerField()),
                ('fooddescription', models.TextField()),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
            },
        ),
    ]
