# Generated by Django 4.2.7 on 2023-12-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='foodimage',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
