# Generated by Django 4.2.7 on 2023-12-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_foodimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='foodimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
